name = "mikoto-relay"
main = "src/index.ts"
compatibility_date = "2026-06-25"

[[durable_objects.bindings]]
name = "RELAY_DO"
class_name = "RelayDurableObject"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["RelayDurableObject"]
